sudo: required
language: bash
services:
- docker
before_install:
- docker build -t jinwuzhao/emacs-cpp .
deploy:
  provider: script
  script: bash docker_push
  on:
    tags: true
env:
  global:
  - secure: HMaEhX4exC9VhA7ToCb6ZXEGawX/y2ncVLjXZBjaP5Js0Neig97ozKmfE3x6xQrs/IAD8AdgzjEg/JiSy2lHeCyzncGyu1GxxFw/FpDmNitwHTu4Wl9ReTnvubw051/KegLcKgZqg0A3Opd2LYa5IdKVmzLBxStMNy7AZxOqdgkSo3tCivAw699lI9O/X6VA97E+OaJ6bO/LvUAbouIRJA+//Da6IoMbuK7B6BFZRXFiR6fa6zICrnusT8H/YecBfr9JEzBjzkMfoaqNoYh4qGDinu6j26jPpuYSouM6El+K02LfVjQ+CnUia2qI+ysHS3+YtcYZTFJGeTz4174pbV5q8ZWdgC5uI0k0BcPps0H1h0Txfu8EjKlFLWyoxh+RCO+gUqxup6w4AWHhMl67x9BzYfpQWQCixfWFWgN0yO6JO6hwzQ6sS7apG63hAkKnjqed+JXB66T48OBHtzPCewYkbx/7tte2iANzKzel1kCtbGblHIi+MmI77xkh6/FSKkUkhCTxsVDVEN8iCxt4XpRhQHtwD7ZLBVBm4y7Gug2KkXuD3yaowHy1H8EQ6OTtcjUqbp8+VVsZ7sOEAtMahCYNSUPgLBm4g9kgkyi4cHIx85U5GrZolDzhWO+tLPnB9ygn7yr/N0j3I+oqmGLBcjqEm4YpvDeulVtNXKr3JRQ=
  - secure: TQKoe8uu1DDLOi45E2jLzbBeh2yPLk0ED1Zw28DSJox/u/ZoSCrVVuk08JMyNipnBJkvcUzz0PdrPLepu2BdRUVnhuP1+ouPmbYqk3fh3ameOWHHqWTh2TsgVSiE+YFinXXbMv8K2vG3DFSw5BHLvJ/jJfB+fbF2Anbq/zzJLpRl9YlqIXI4ejAeC7A/WcfPArXl9Z2f6ZLcC72tc8pBcLm6ysgMmNx2yAOJW53OcFkI3J/u4y1Y9RqQaDP0aZVSybB/gn+hFekA1kN7RpKHMVRNsu4I69dtqazX9RI7H/ilQ7z72v32rWS2TolzL9iuYNQ4fjMjFLJPJ6jZD4cK37x5hc+nXogDA5bjyvhBD3Ftw+eedOyXzpNB7X39s7JkQbYOXzt4iBoITYEs31mF2rVqt11OPHhTFD49cAqggbgyUjyGmHaiNvd9kHAcfSQ6Ck9Ft+8ksFuJYAeLwldURY1LABGnDCUwqoNQGfQGkgb8gyc1S65mVu45ACGmewMom5YIRORvszv8wH+FVHajhUs94VtymLMPkfCQDXe56SG9bpY3xNFzLM+X7kCBq8/fkU0liMvhgPmm2ztIMrA/NUZLXy80ZN0N+BhCbtrvot7NqNN77NhDHWGwR3Mom75jTehc/kROU1+2v/O9R0kXCeBleZJ7jfT+DnYNM69vebk=
